### ISSUE TITLE
Bicycle count for Neutor broken

### ISSUE THREAD

**Issue by christophfriedrich** [reedu-reengineering-education/smart-city-dashboard-backend#3]
The count always shows as 0. The corresponding request https://city-dashboard.felixerdmann.com/bicycle/100035541 just returns the empty array `[]`.

**Comment by Smart-City-Muenster** [comment]
Thanks for reporting. That's actually a hardware fault of the sensor. Our colleagues are aware of the problem and try to fix it as soon as possible.

**Comment by Smart-City-Muenster** [comment]
Closing because it's not software-related.
